/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Inicio.java
 *
 * Created on 20/03/2011, 04:15:15 PM
 */
package capa_presentacion;

import capa_datos.ConectarBD;
import DAO.DAO;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author usuario
 */
public class Inicio extends javax.swing.JFrame {

    private Connection dbConecta;
    private String CadenaSql;
    private ResultSet rs;
    private Statement statement = null;

    public Inicio() {
        initComponents();
        PnlFondo pnlfondo = new PnlFondo();
        this.add(pnlfondo,BorderLayout.CENTER);
        this.pack();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ingresoEstu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passestud = new javax.swing.JPasswordField();
        passadmin = new javax.swing.JPasswordField();
        codigoAdmin = new javax.swing.JTextField();
        codigoestudiante = new javax.swing.JTextField();
        ingresoadm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Razer Header Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("CODIGO ADMINISTRADOR:");

        jLabel4.setFont(new java.awt.Font("Razer Header Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("CODIGO ESTUDIANTE:");

        ingresoEstu.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ingresoEstu.setText("Ingresar");
        ingresoEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoEstuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Razer Header Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("CONTRASEÑA:");

        jLabel6.setFont(new java.awt.Font("Razer Header Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("CONTRASEÑA:");

        passestud.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        passadmin.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        codigoAdmin.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        codigoestudiante.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        ingresoadm.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ingresoadm.setText("Ingresar");
        ingresoadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoadmActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capa_presentacion/recursos/header_home_page3.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(codigoAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(passadmin)
                    .addComponent(codigoestudiante)
                    .addComponent(passestud))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingresoEstu)
                    .addComponent(ingresoadm))
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(codigoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresoadm))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ingresoEstu)
                    .addComponent(codigoestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passestud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoEstuActionPerformed
        DAO SQ = new DAO();
        ConectarBD CBD = new ConectarBD("localhost", "5432", "ApoyoAlimentario", "postgres", "bmx92103057509");
        CBD.SetCadena(SQ.AccesoEstudiante(codigoestudiante.getText(), passestud.getText()));


    }//GEN-LAST:event_ingresoEstuActionPerformed

    private void ingresoadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoadmActionPerformed
        DAO SQ = new DAO();
        ConectarBD CBD = new ConectarBD("localhost", "5432", "ApoyoAlimentario", "postgres", "bmx92103057509");
        CBD.SetCadena(SQ.AccesoAdmin(codigoAdmin.getText(), passadmin.getText()));
    }//GEN-LAST:event_ingresoadmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoAdmin;
    private javax.swing.JTextField codigoestudiante;
    private javax.swing.JButton ingresoEstu;
    private javax.swing.JButton ingresoadm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField passadmin;
    private javax.swing.JPasswordField passestud;
    // End of variables declaration//GEN-END:variables
}
